version: '3'
services:
  frontend:
    container_name: todo-frontend
    build:
      context: frontend
    ports:
      - "3000:3000"

  backend:
    container_name: todo-backend
    build:
      context: backend
    ports:
      - "8090:8080"