version: '3'
services:
  frontend:
    container_name: todo-frontend
    build:
      context: frontend
    image: todo:latest
    ports:
      - "3000:3000"

  backend:
    container_name: todo-backend
    build:
      context: backend
    image: todo:latest
    ports:
      - "8090:8080"
    depends_on:
      - psql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  psql:
    image: 'postgres'
    container_name: psql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"