spring:
  liquibase:
    url: jdbc:h2:mem:test_task;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS test_task
    change-log: classpath:db/changelog/liquibase-changeLog.xml
    default-schema: test_task
    password: ''
    enabled: true
    user: sa
  application:
    name: Test task
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:test_task
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
app:
  user:
    verification:
      email:
        message:
          successfully: Добрый день, %s %s %s! Верификация прошла успешно
          unsuccessfully: Добрый день, %s %s %s! Верификация прошла не успешно
        subject: Верфиикация аккаунта в ${spring.application.name}
  register:
    message:
      email-existing: Аккаунт с такой почтой уже существует
      login-existing: Аккаунт с таким логином уже существует
      unsuccessful: Произошла ошибка. Попробуйте позже
server:
  port: '8080'