spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: admin
    password: admin
    driverClassName:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect=org:
          hibernate:
            dialect:
              PostgreSQL10Dialect

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR