spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://rc1a-wlws7dv1978nkeqb.mdb.yandexcloud.net:6432/todo
    username: my-brand-new-user
    password: password-for-my-brand-new-user
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect=org:
          hibernate:
            dialect:
              PostgreSQL10Dialect

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR